### ISSUE TITLE
Installing seems to load full CRAN library

### ISSUE THREAD

**Issue by dsolito** [JohnCoene/grapher#2]
Thank you again for this package.
When I tried to install the package as written on the guide:

`remotes::install_github('JohnCoene/grapher', dependencies = c("Depends", "Imports", "Suggests"))`

seems that the full CRAN library is downloaded when you agree to update the installed package. (same package are downlaoded as showed here : https://cran.r-project.org/bin/macosx/el-capitan/contrib/3.5/)

Maybe is due to the cran_deps_graph() function?

Solution was to abort the session and the downloads and install the package as showed on github : 
`remotes::install_github("JohnCoene/grapher")`

**Comment by JohnCoene** [comment]
Thanks this should be fixed now.
