### ISSUE TITLE
add node/link online

### ISSUE THREAD

**Issue by robocop-bob** [JohnCoene/grapher#27]
Congratulations. A great package.

The current documentation describes some great examples. You can see that it is easy to display the graph, change the attributes of a node or a connection.

Is it possible now to add a new node/connection without having to refresh the whole graph? If so, it would be great to expand the documentation with an example of a data stream from Twitter https://rdrr.io/cran/rtweet/man/stream_tweets.html

**Comment by JohnCoene** [comment]
Yes.

You can run `grapher_demo()` for examples of shiny integration.

The source code is fairly simple and short: https://github.com/JohnCoene/grapher/blob/master/inst/app/app.R

**Comment by ghost** [comment]
Thx, it works :)
