### ISSUE TITLE
Camera FOV function only for shiny apps?

### ISSUE THREAD

**Issue by dsolito** [JohnCoene/grapher#4]
` graph(network) %>% 
  graph_layout_offline() %>% 
  scale_node_size(degree, c(6, 50)) %>% 
  scale_node_color(group, palette = c("yellow", "white")) %>% 
  scale_link_color_coords() %>% 
  graph_camera_fov(fov = 75L)`

`Error in UseMethod("graph_camera_fov") : no applicable method for 'graph_camera_fov' applied to an object of class "c('graph', 'htmlwidget')"`

**Comment by JohnCoene** [comment]
OK, sorted.

```r
library(grapher)

graph(g) %>% 
  graph_camera_fov(120)
```
