### ISSUE TITLE
question

### ISSUE THREAD

**Issue by gutama** [JohnCoene/grapher#5]
Hi, 
I already installed grapher using remote but somehow the graph did not appear in RStudio,
but no errors returned. Just blank

library(grapher)
g <- make_data(50)
> graph(g)
Registered S3 method overwritten by 'jsonify':
  method     from    
  print.json jsonlite

no graph at all, please help

Thank you

**Comment by JohnCoene** [comment]
That's an issue with RStudio, I'll look into it. Can you open it in the browser, this should work.

**Comment by gutama** [comment]
how to open it in the browser, I just run it as Rmd file or ordinary R file? Should I put it in a Shiny app?

**Comment by JohnCoene** [comment]
It should work in the RStudio IDE, you might be on a well outdated version. If I were I would update RStdudio. If this still does not show a graph. then open it in the browser (see screenshot below).

![g](https://user-images.githubusercontent.com/7833796/77850934-25d6de00-71d6-11ea-914f-4249c59c174b.png)

**Comment by gutama** [comment]
it works on browser by opening new window,
updated RStudio to Version 1.2.5033,
but still not worked on Rmd page, is it normal? because the js things perhaps.

![image](https://user-images.githubusercontent.com/1462448/77877624-7440b700-7280-11ea-8851-488861ae45ec.png)

thank you and kind regards

**Comment by JohnCoene** [comment]
Could you share your template Rmarkdown? It should work.

**Comment by gutama** [comment]
---
title: "Untitled"
author: "Ginanjar Utama"
date: "30/3/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

This is an R Markdown document. Markdown is a simple formatting syntax for authoring HTML, PDF, and MS Word documents. For more details on using R Markdown see <http://rmarkdown.rstudio.com>.

When you click the **Knit** button a document will be generated that includes both content as well as the output of any embedded R code chunks within the document. You can embed an R code chunk like this:

```{r cars}
summary(cars)
```

## Including Plots

You can also embed plots, for example:

```{r pressure, echo=FALSE}
plot(pressure)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.

```{r}
library(grapher)

g <- make_data(50)

head(g)

graph(g)
```

**Comment by gutama** [comment]
It just the default template from RStudio, I am in windows environment

**Comment by gutama** [comment]
![image](https://user-images.githubusercontent.com/1462448/77885410-2e401f00-7291-11ea-9c07-4daefb89f6ae.png)

**Comment by JohnCoene** [comment]
This works fine on my end, it may not show in the preview.

![image](https://user-images.githubusercontent.com/7833796/77885465-587ce700-7267-11ea-8f67-390870c693be.png)

**Comment by gutama** [comment]
I see, I have to knit it to HTML first, it doesn't work in HTML preview from RStudio, but worked fine in chrome.

Thanks
